### ISSUE TITLE
Steam not recognizing new folder

### ISSUE THREAD

**Issue by tsuchodolski** [LostDragonist/steam-library-setup-tool#4]
Hi!

I downloaded the tool and followed the instructions. I ran the tool as administrator from the downloads folder, and made a new folder for steam in C:\
![Capture](https://user-images.githubusercontent.com/58183347/106955032-a4f44700-6702-11eb-8898-f255727ee63a.PNG)

But when I start steam again, it doesn't show up

![Capture2](https://user-images.githubusercontent.com/58183347/106955117-c8b78d00-6702-11eb-86fc-501dd3a371df.PNG)

Any thoughts?

**Comment by LostDragonist** [comment]
I'd imagine the problem is that you can't make your entire drive a Steam library.

**Comment by tsuchodolski** [comment]
Yep, going one subfolder down does the trick
