### ISSUE TITLE
Windows Detecting Build as Malware

### ISSUE THREAD

**Issue by nenmyx** [LostDragonist/steam-library-setup-tool#5]
Windows Security is picking up the .exe release of this tool as a `Glupteba!ml` trojan and will not allow me to execute it.

**Comment by LostDragonist** [comment]
I'm not able to reproduce that result locally, though I'll admit that could mean nothing.  [VirusTotal](https://www.virustotal.com/gui/file/84e4cce9cc759beb92aa6e49d63861b6693dcf2aaa2839db8d34a19cf9fdd37d/detection) does have some detections by smaller vendors but nothing by the more major vendors.

/shrug.  Don't really think there's much I can do about it.  On your side, you could tell Windows Defender to knock it off and allow the file.  Maybe submit the file to Microsoft for analysis.
