### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by MaserSgtWoods** [LostDragonist/steam-library-setup-tool#7]
I keep getting this error saying "error when creting new directories" i dont know what to do.
![2021-08-10](https://user-images.githubusercontent.com/88752783/128953039-c0692597-5639-4522-9624-a29c2489131d.png)

**Comment by LostDragonist** [comment]
Do you have a D: drive?  If you do, then it seems like the tool is being prevented from creating the folder so maybe you'd just want to create it yourself.  Specifically, for the image you posted, you'd need to create the folder `D:\Games\Steam Library\steamapps`.
